### ISSUE TITLE
Optimize Your Images - add error messeages 

### ISSUE THREAD

**Issue by AmitT** [win-site/winsite-image-optimizer#1]
Tried to regenerate retroactive and the page refreshed without any feedback.

**Comment by maor** [comment]
Can you please let me know what happens in the console? 

Also please look at the "Network" tab in the Web Developer Tool, since clicking on the button triggers a JS callback in `assets/js/winsite-image-optimizer.js`.

**Comment by AmitT** [comment]
Probably the error is "API username is missing" :-) but i'll check it later.

**Comment by AmitT** [comment]
Nothing in the console about it.
`winsite-image-optimizer.js` returns 404. it refers to wrong folder.

**Comment by jessefisher** [comment]
The assets directory is missing from the plugin. I uploaded it manually and the Regenerate Retroactive button works.

Adding a loading gif would help indicate it has started. I wasn't sure because it only adds the labels as each image is completed and it had to run through 10 thumbnails first in my case.

**Comment by maor** [comment]
> The assets directory is missing from the plugin. I uploaded it manually and the Regenerate Retroactive button works.

This just got fixed.

> Adding a loading gif would help indicate it has started. I wasn't sure because it only adds the labels as each image is completed and it had to run through 10 thumbnails first in my case.

Definitely important. I've added the built-in WP spinner for better UX in the last release (1.0.2). Thank you for the great feedback, @jessefisher!
