### ISSUE TITLE
Keep original deletes original

### ISSUE THREAD

**Issue by jessefisher** [win-site/winsite-image-optimizer#2]
I had Keep Original checked and ran Regenerate Retroactive (after manually uploading the missing JS) and it deleted the original file, but kept all of its thumbnails.

**Comment by maor** [comment]
Bug too... will fix! Thanks, @jessefisher.

**Comment by maor** [comment]
Made a few tests and now seems to work okay.

You should be able to update the plugin via the built-in plugin updater in WP, and the assets directory should be there (has been renamed to `static` for now).

Please LMK if this works  :)
