### ISSUE TITLE
Installation - Fatal error during activation

### ISSUE THREAD

**Issue by borshpro** [win-site/winsite-image-optimizer#8]
### Fatal error during activation

- Plugin installation via 'Add New' plugin – OK.
- But after pressing 'Activate', getting **fatal error** while activating.  

Quote form WP:
> 
> Plugin could not be activated because it triggered a fatal error.
> 
> **Parse error**: syntax error, unexpected ':' in <...>/www/wp-content/plugins/winsite-image-optimizer/includes/**class-wsi-retro-processor.php** on line **171**

**Comment by AmitT** [comment]
@borshpro 
Thank you for reporting, and sorry for the late response.
Fixed. Please report if you still having any issues.
